CREATE TABLE SERVERSTAT (
  time TIMESTAMP,
  ami_id STRING,
  ami_launch_index INT,
  availability_zone STRING,
  conns_per_sec INT,
  cpu_count INT,
  cpu_usage FLOAT,
  cpu_idle FLOAT,
  cpu_stolen FLOAT,
  disk_iops FLOAT,
  free_memory FLOAT,
  instance_id STRING,
  instance_type STRING,
  load_1 FLOAT,
  load_15 FLOAT,
  load_5 FLOAT,
  private_hostname STRING,
  private_ipv4 IP,
  public_hostname STRING,
  public_ipv4 IP,
  reservation_id STRING,
  security_groups STRING,
  server_type STRING,
  total_memory FLOAT,
  used_memory FLOAT,
  network_inbound_kbps FLOAT,
  network_outbound_kbps FLOAT,
  network_inbound_mbps FLOAT,
  network_outbound_mbps FLOAT,
  venom_www_build STRING,
  venom_www_release STRING,
  venom_www_version FLOAT,
  autoscale_group STRING,
  autoscale_persist INT
) CLUSTERED INTO 4 shards WITH (
  number_of_replicas = 1,
  refresh_interval = 500);